name: Amore
main: space.minota.amore.Main
version: 0.0.1
description: Xestra's main plugin core.
author: Minota
soft-depend: Vault
commands:
  heal:
      description: Heals you or a given player.
  feed:
      description: Feeds you or a given player.
  ci:
      description: Clears you or a given player's inventory.
      aliases:
        - clear
  cleareffects:
    description: Clears you or a given player's potion effects.
    aliases:
      - ce
  fly:
    description: Toggles you or a given player's flight.
  gm:
    description: Changes you or a provided player's gamemode.
  gamemode:
    description: Changes you or a provided player's gamemode.
  gmsp:
    description: Changes you or a provided player's gamemode to Spectator.
  gmc:
    description: Changes you or a provided player's gamemode to Creative.
  gms:
    description: Changes you or a provided player's gamemode to Survival.
  gma:
    description: Changes you or a provided player's gamemode to Adventure.
  msg:
    aliases:
      - message
      - tell
      - whisper
      - w
    description: Privately message a user.